# -*- coding: utf-8 -*-
"""evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKbWQJO_JZwvPBWO8AJTzGb1GJe1ZRSa
"""

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score
)

class Evaluator:
    def evaluate(self, model, X_test, y_test, model_name):
        # Prediction
        y_pred = model.predict(X_test)

        # Metrics
        accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        report = classification_report(y_test, y_pred)

        # Print Result
        print(f"\n{'=' * 40}")
        print(f"Model    : {model_name}")
        print(f"Accuracy : {accuracy:.4f}")
        print(f"F1 Score : {f1:.4f}")
        print("=" * 40)
        print(report)

        # Return Metrics
        return {
            "accuracy": accuracy,
            "f1_score": f1,
            "classification_report": report
        }