# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBXiF2NNBJNNmya6O19zKh-J2z1HxURT
"""

import streamlit as st
import pandas as pd
import joblib

import streamlit as st
import pandas as pd
import joblib

# PAGE CONFIG
st.set_page_config(
    page_title="Credit Score Prediction",
    page_icon="💳",
    layout="wide"
)

# LOAD MODEL
model = joblib.load("best_model.pkl")

# HEADER
st.markdown("""
<h1 style='text-align:center;color:#0066CC;'>
💳 Credit Score Prediction System
</h1>

<h4 style='text-align:center;color:gray;'>
Machine Learning Deployment using Streamlit
</h4>

<hr>
""", unsafe_allow_html=True)

# INPUT
st.subheader("👤 Customer Information")

col1, col2 = st.columns(2)

with col1:

    Age = st.number_input("Age", 18, 100, 30)

    Occupation = st.selectbox(
        "Occupation",
        [
            "Scientist",
            "Teacher",
            "Engineer",
            "Doctor",
            "Lawyer",
            "Media_Manager",
            "Manager",
            "Entrepreneur",
            "Mechanic",
            "Developer",
            "Writer",
            "Architect",
            "Musician",
            "Accountant",
            "Journalist"
        ]
    )

    Annual_Income = st.number_input(
        "Annual Income",
        value=50000.0
    )

    Monthly_Inhand_Salary = st.number_input(
        "Monthly Inhand Salary",
        value=4000.0
    )

    Num_Bank_Accounts = st.number_input(
        "Number of Bank Accounts",
        value=3
    )

    Num_Credit_Card = st.number_input(
        "Number of Credit Cards",
        value=2
    )

    Interest_Rate = st.number_input(
        "Interest Rate",
        value=8
    )

    Num_of_Loan = st.number_input(
        "Number of Loans",
        value=2
    )

    Delay_from_due_date = st.number_input(
        "Delay from Due Date",
        value=5
    )

    Num_of_Delayed_Payment = st.number_input(
        "Delayed Payments",
        value=2
    )

with col2:

    Changed_Credit_Limit = st.number_input(
        "Changed Credit Limit",
        value=5.0
    )

    Num_Credit_Inquiries = st.number_input(
        "Credit Inquiries",
        value=2
    )

    Credit_Mix = st.selectbox(
        "Credit Mix",
        [
            "Good",
            "Standard",
            "Bad"
        ]
    )

    Outstanding_Debt = st.number_input(
        "Outstanding Debt",
        value=1000.0
    )

    Credit_Utilization_Ratio = st.number_input(
        "Credit Utilization Ratio",
        value=30.0
    )

    Credit_History_Age = st.number_input(
        "Credit History (Months)",
        value=120
    )

    Payment_of_Min_Amount = st.selectbox(
        "Payment of Minimum Amount",
        [
            "Yes",
            "No"
        ]
    )

    Total_EMI_per_month = st.number_input(
        "Total EMI per Month",
        value=120.0
    )

    Amount_invested_monthly = st.number_input(
        "Amount Invested Monthly",
        value=150.0
    )

    Payment_Behaviour = st.selectbox(
        "Payment Behaviour",
        [
            "High_spent_Small_value_payments",
            "High_spent_Medium_value_payments",
            "High_spent_Large_value_payments",
            "Low_spent_Small_value_payments",
            "Low_spent_Medium_value_payments",
            "Low_spent_Large_value_payments"
        ]
    )

    Monthly_Balance = st.number_input(
        "Monthly Balance",
        value=400.0
    )

# DATAFRAME
input_df = pd.DataFrame({

    "Age":[Age],
    "Occupation":[Occupation],
    "Annual_Income":[Annual_Income],
    "Monthly_Inhand_Salary":[Monthly_Inhand_Salary],
    "Num_Bank_Accounts":[Num_Bank_Accounts],
    "Num_Credit_Card":[Num_Credit_Card],
    "Interest_Rate":[Interest_Rate],
    "Num_of_Loan":[Num_of_Loan],
    "Delay_from_due_date":[Delay_from_due_date],
    "Num_of_Delayed_Payment":[Num_of_Delayed_Payment],
    "Changed_Credit_Limit":[Changed_Credit_Limit],
    "Num_Credit_Inquiries":[Num_Credit_Inquiries],
    "Credit_Mix":[Credit_Mix],
    "Outstanding_Debt":[Outstanding_Debt],
    "Credit_Utilization_Ratio":[Credit_Utilization_Ratio],
    "Credit_History_Age":[Credit_History_Age],
    "Payment_of_Min_Amount":[Payment_of_Min_Amount],
    "Total_EMI_per_month":[Total_EMI_per_month],
    "Amount_invested_monthly":[Amount_invested_monthly],
    "Payment_Behaviour":[Payment_Behaviour],
    "Monthly_Balance":[Monthly_Balance]
})

# PREDICT
if st.button("🔍 Predict Credit Score", use_container_width=True):

    prediction = model.predict(input_df)[0]

    labels = {
        0: "Poor",
        1: "Standard",
        2: "Good"
    }

    result = labels[prediction]

    st.markdown("---")

    st.subheader("🎯 Prediction Result")

    if result == "Good":

        st.success(f"🟢 {result}")

    elif result == "Standard":

        st.warning(f"🟡 {result}")

    else:

        st.error(f"🔴 {result}")

# FOOTER
st.markdown("---")

st.info("""
### 📘 Credit Score Categories

🟢 **Good**
Customer has excellent credit behavior.

🟡 **Standard**
Customer has average credit behavior.

🔴 **Poor**
Customer has poor credit behavior.
""")