# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqhXK2_UHR0HnFpjX_WeQKwKDWkHCNYx
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

class Preprocessor:
    def __init__(self, file_path):
        self.file_path = file_path
        self.preprocessor = None

    def load_data(self):
        return pd.read_csv(self.file_path)

    def clean_numeric(self, col):
        col = col.astype(str)
        col = col.str.replace("_", "", regex=False)
        col = col.str.replace(",", "", regex=False)
        col = col.str.replace("$", "", regex=False)
        col = col.str.extract(r"([-]?\d+\.?\d*)")[0]
        return pd.to_numeric(col, errors="coerce")

    def convert_credit_history(self, age_str):

        if pd.isna(age_str):
            return np.nan

        years = int(age_str.split("Years")[0].strip())
        months = int(age_str.split("and")[1].split("Months")[0].strip())

        return years * 12 + months

    def preprocess(self):
        df = self.load_data()

        # Drop Column
        drop_cols = [
            "Unnamed: 0",
            "ID",
            "Customer_ID",
            "Name",
            "SSN",
            "Month",
            "Type_of_Loan"
        ]

        df.drop(columns=drop_cols, errors="ignore", inplace=True)

        # Drop Duplicate
        df.drop_duplicates(inplace=True)

        # Numeric Cleaning
        numeric_cols = [
            "Age",
            "Annual_Income",
            "Num_of_Loan",
            "Num_of_Delayed_Payment",
            "Changed_Credit_Limit",
            "Outstanding_Debt",
            "Amount_invested_monthly",
            "Monthly_Balance"
        ]

        for col in numeric_cols:
            df[col] = self.clean_numeric(df[col])

        # Credit History
        df["Credit_History_Age"] = (
            df["Credit_History_Age"]
            .apply(self.convert_credit_history)
        )

        # Invalid Negative
        invalid_negative = [
            "Age",
            "Num_Bank_Accounts",
            "Num_Credit_Card",
            "Delay_from_due_date"
        ]

        for col in invalid_negative:
            df.loc[df[col] < 0, col] = np.nan

        # Missing Value
        num_cols = df.select_dtypes(include=["int64", "float64"]).columns

        for col in num_cols:
            df[col] = df[col].fillna(df[col].median())


        # Invalid Category
        df["Occupation"] = df["Occupation"].replace(
            "_______",
            np.nan
        )

        df["Credit_Mix"] = df["Credit_Mix"].replace(
            "_",
            np.nan
        )

        df["Payment_Behaviour"] = (
            df["Payment_Behaviour"]
            .str.replace(r"[^a-zA-Z_ ]", "", regex=True)
        )

        # Missing Value
        cat_cols = df.select_dtypes(include="object").columns
        for col in cat_cols:
            df[col] = df[col].fillna(df[col].mode()[0])

        # Outlier
        for col in num_cols:
            upper = df[col].quantile(0.95)
            lower = df[col].quantile(0.05)

            df[col] = np.clip(
                df[col],
                lower,
                upper
            )

        # Split Feature Target
        X = df.drop("Credit_Score", axis=1)

        y = df["Credit_Score"].map({
            "Poor": 0,
            "Standard": 1,
            "Good": 2
        })

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.2,
            random_state=42,
            stratify=y
        )

        # Encoder
        cat_cols = X_train.select_dtypes(include="object").columns

        self.preprocessor = ColumnTransformer(
            transformers=[
                (
                    "cat",
                    OneHotEncoder(handle_unknown="ignore"),
                    cat_cols
                )
            ],
            remainder="passthrough"
        )

        return (
            X_train,
            X_test,
            y_train,
            y_test,
            self.preprocessor
        )