# -*- coding: utf-8 -*-
"""trainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcd271PjbxfxzDgWefd1n5yOmNFYYg5f
"""

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

class Trainer:
    def __init__(self, preprocessor):
        self.preprocessor = preprocessor

    # Random Forest
    def random_forest_base(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", RandomForestClassifier(
                random_state=42
            ))
        ])

    def random_forest_tuned(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", RandomForestClassifier(
                n_estimators=300,
                max_depth=20,
                min_samples_split=5,
                min_samples_leaf=2,
                class_weight="balanced",
                random_state=42
            ))
        ])

    # XGBoost
    def xgb_base(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", XGBClassifier(
                eval_metric="mlogloss",
                random_state=42
            ))
        ])

    def xgb_tuned(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", XGBClassifier(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=6,
                subsample=0.8,
                colsample_bytree=0.8,
                eval_metric="mlogloss",
                random_state=42
            ))
        ])

    # Logistic Regression
    def logistic_base(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", LogisticRegression(
                max_iter=1000,
                random_state=42
            ))
        ])

    def logistic_tuned(self):
        return Pipeline(steps=[
            ("preprocess", self.preprocessor),
            ("model", LogisticRegression(
                max_iter=1000,
                C=0.5,
                solver="lbfgs",
                random_state=42
            ))
        ])

    # Semua Model
    def get_models(self):
        return {
            "Random Forest Base": self.random_forest_base(),
            "Random Forest Tuned": self.random_forest_tuned(),
            "XGBoost Base": self.xgb_base(),
            "XGBoost Tuned": self.xgb_tuned(),
            "Logistic Base": self.logistic_base(),
            "Logistic Tuned": self.logistic_tuned()
        }