# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4vcTAePfXrkyZtCEJ3tC_PKRkjPoLp1
"""

import joblib
import mlflow
import mlflow.sklearn

from preprocessing import Preprocessor
from trainer import Trainer
from evaluator import Evaluator

mlflow.sklearn._logger.setLevel("ERROR")

def main():
    # Data Preprocessing
    prep = Preprocessor("data_B.csv")

    X_train, X_test, y_train, y_test, preprocessor = prep.preprocess()

    # Trainer & Evaluator
    trainer = Trainer(preprocessor)
    evaluator = Evaluator()

    models = trainer.get_models()

    best_model = None
    best_model_name = None
    best_f1 = -1

    # MLflow Experiment
    mlflow.set_experiment("Credit Scoring")

    for name, model in models.items():
        with mlflow.start_run(run_name=name):
            print(f"\nTraining {name}...")

            # Training
            model.fit(X_train, y_train)

            # Evaluation
            metrics = evaluator.evaluate(
                model=model,
                X_test=X_test,
                y_test=y_test,
                model_name=name
            )

            # MLflow Logging
            # Nama model
            mlflow.log_param("model_name", name)

            # Hyperparameter classifier
            classifier = model.named_steps["model"]
            mlflow.log_params(classifier.get_params())

            # Metrics
            mlflow.log_metric("accuracy", metrics["accuracy"])
            mlflow.log_metric("f1_score", metrics["f1_score"])

            # Simpan model ke MLflow
            mlflow.sklearn.log_model(
                sk_model=model,
                artifact_path="model",
                serialization_format="cloudpickle"
            )

            # Best Model
            if metrics["f1_score"] > best_f1:

                best_f1 = metrics["f1_score"]
                best_model = model
                best_model_name = name

    # Validasi Best Model
    if best_model is None:
        raise RuntimeError("Tidak ada model yang berhasil dilatih.")

    # Save Best Model
    print("\n==============================")
    print("Training Finished")
    print("==============================")
    print(f"Best Model   : {best_model_name}")
    print(f"Best F1 Score: {best_f1:.4f}")

    joblib.dump(
        best_model,
        "best_model.pkl"
    )
    print("Best model saved as best_model.pkl")

    # Log Best Model
    with mlflow.start_run(run_name="Best Model"):
        mlflow.set_tag(
            "stage",
            "best_model"
        )

        mlflow.log_param(
            "best_model",
            best_model_name
        )

        mlflow.log_metric(
            "best_f1_score",
            best_f1
        )

        mlflow.sklearn.log_model(
            sk_model=best_model,
            artifact_path="best_model",
            serialization_format="cloudpickle"
        )


if __name__ == "__main__":
    main()